# Generated by Django 4.0.5 on 2022-08-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_ascontact_address2_alter_ascontact_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascontact',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
