# Generated by Django 4.0.5 on 2022-07-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_ascontact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ascontact',
            name='uuid',
        ),
    ]
