# Generated by Django 4.0.5 on 2022-07-04 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matters', '0002_alter_matter_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('VID', 'Video Conf'), ('OHO_HEAR', 'OHO Hearing'), ('MEET', 'Meeting'), ('UNK', 'Unknown')], default='UNK', max_length=10)),
                ('StartDateTime', models.DateTimeField(null=True)),
                ('Length', models.IntegerField(default=30)),
                ('EndDateTime', models.DateTimeField(null=True)),
                ('Attendees', models.CharField(max_length=60, null=True)),
                ('location', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANC', 'Cancelled'), ('DONE', 'Done'), ('UNK', 'Unknown')], default='StatusType.UNKNOWN', max_length=10)),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_created_by', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_matter', to='matters.matter')),
            ],
            options={
                'ordering': ['priority', 'created_date'],
            },
        ),
    ]
