# Generated by Django 4.0.5 on 2022-07-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('matters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_matters', to='matters.matter'),
        ),
    ]
