# Generated by Django 4.0.5 on 2022-07-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('SCHED', 'Scheduled'), ('CANC', 'Cancelled'), ('DONE', 'Done'), ('ONHOLD', 'On Hold'), ('OTHER', 'Other')], default='StatusType.OTHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('CALL', 'Call'), ('CONF', 'Conference'), ('DEAD', 'Deadline'), ('VID', 'Video Conf'), ('OHO_HEAR', 'OHO Hearing'), ('MEET', 'Meeting'), ('PRES', 'Presentation'), ('OTHER', 'Other'), ('WARN', 'Deadline Warning')], default='OTHER', max_length=10),
        ),
    ]
