# Generated by Django 4.0.5 on 2022-07-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Call'), (3, 'Conference'), (4, 'Deadline'), (5, 'Video Conf'), (6, 'OHO Hearing'), (7, 'Meeting'), (8, 'Presentation'), (9, 'Other'), (10, 'Deadline Warning')], default=1),
        ),
    ]
