# Generated by Django 4.0.5 on 2022-07-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='matter',
        ),
    ]
