# Generated by Django 4.0.5 on 2022-07-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_status_alter_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EndDateTime',
        ),
    ]
