# Generated by Django 4.0.5 on 2022-08-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_location_url_alter_event_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Pending'), (3, 'Cancelled'), (4, 'Done'), (5, 'On Hold'), (6, 'Other'), (7, 'Scheduled'), (8, 'Wait to be rescheduled')], default=2),
        ),
    ]
