# Generated by Django 4.0.5 on 2022-07-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['priority', 'created']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_date',
            new_name='created',
        ),
    ]
