# Generated by Django 4.0.5 on 2022-07-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_assigned_to_alter_event_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Attendees',
            new_name='attendees',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Length',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='StartDateTime',
            new_name='startdatetime',
        ),
    ]
