# Generated by Django 4.0.5 on 2022-07-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_options_rename_created_by_event_added_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='title',
            field=models.CharField(default='x12s', max_length=150),
            preserve_default=False,
        ),
    ]
