# Generated by Django 4.0.5 on 2022-07-31 14:47

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kbentries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbentry',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='kbentry',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kbentrycategory',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='kbentrycategory',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
