# Generated by Django 4.0.5 on 2022-07-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbentries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kbentry',
            options={'verbose_name_plural': 'KBase entries'},
        ),
    ]
