# Generated by Django 4.0.5 on 2022-08-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbentries', '0002_alter_kbentry_datetime_alter_kbentry_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbentry',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='kbentrycategory',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
