# Generated by Django 4.0.5 on 2022-07-25 19:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('kbentries', '0002_alter_kbentry_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kbentry',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='kbentry',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='kbentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='kbentry',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='kbentry',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='kbentrycategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='kbentrycategory',
            name='files_foldername',
        ),
        migrations.RemoveField(
            model_name='kbentrycategory',
            name='name',
        ),
        migrations.AddField(
            model_name='kbentry',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kbentry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kbentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 25, 19, 55, 26, 672692, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kbentry',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kbentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kbentry',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kbentry',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kbentrycategory',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kbentrycategory',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kbentrycategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 25, 19, 55, 49, 34007, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kbentrycategory',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kbentrycategory',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kbentrycategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kbentrycategory',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='kbentrycategory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kbentry',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kbentry',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='kbentry',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kbentrycategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
