# Generated by Django 4.0.5 on 2022-07-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
