# Generated by Django 4.0.5 on 2022-08-01 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssoffices', '0006_ssstaff_ssoffices_s_type_b3eed0_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssstaff',
            old_name='last_modified_by',
            new_name='modified_by',
        ),
        migrations.RemoveField(
            model_name='ssoffice',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ssoffice',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ssoffice',
            name='servicing_fos',
        ),
        migrations.RemoveField(
            model_name='ssoffice',
            name='servicing_ssns',
        ),
        migrations.RemoveField(
            model_name='ssoffice',
            name='servicing_states',
        ),
        migrations.RemoveField(
            model_name='ssoffice',
            name='servicing_zipcodes',
        ),
        migrations.RemoveField(
            model_name='ssstaff',
            name='city',
        ),
        migrations.AddField(
            model_name='ssoffice',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssoffice',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ssoffice',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ssoffice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ssoffice',
            name='slug',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ssoffice',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ssoffice',
            name='type',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Field Office (FO)'), (3, 'Disability Determination Services (DDS)'), (4, 'Office of Hearings Operations (OHO)'), (5, 'Appeals Council (AC)'), (6, 'Program Service Center (PSC)'), (7, 'PC Mod (PC MOD'), (8, 'Regional Office (RO)'), (9, 'National Hearing Center (NHC)'), (10, 'Central Scheduling Unit (CSU)'), (11, 'National Case Assistance Center (NCAC'), (12, 'Workload Support Unit (WSU)'), (13, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='ssstaff',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
