# Generated by Django 4.0.5 on 2022-07-31 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeping', '0002_alter_worksession_options_worksession_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
