# Generated by Django 4.0.5 on 2022-08-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeping', '0003_alter_worksession_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
