# Generated by Django 4.0.5 on 2022-07-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0002_alter_matter_tags'),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_list',
        ),
        migrations.AddField(
            model_name='task',
            name='matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matters.matter'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
