# Generated by Django 4.0.5 on 2022-07-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_taskcategory_remove_task_type_delete_tasktype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name_plural': 'task categories'},
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Call'), (3, 'Wait'), (4, 'Email'), (5, 'Draft'), (6, 'Review'), (7, 'Send'), (8, 'Other')], default=1),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='type',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Call'), (3, 'Wait'), (4, 'Email'), (5, 'Draft'), (6, 'Review'), (7, 'Send'), (8, 'Other')], default=1),
        ),
    ]
