# Generated by Django 4.0.5 on 2022-07-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_task_task_list_task_matter_delete_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('CALL', 'Call'), ('DRAFT', 'Draft Doc'), ('UNK', 'Unknown')], default='UNK', max_length=15),
        ),
    ]
