# Generated by Django 4.0.5 on 2022-07-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('CALL', 'Call'), ('DRAFT', 'Draft Doc'), ('OTHER', 'Other')], default='OTHER', max_length=15),
        ),
    ]
