# Generated by Django 4.0.5 on 2022-07-20 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseentry',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entrycategory',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2022, 7, 20, 18, 44, 53, 414399, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
