# Generated by Django 4.0.5 on 2022-07-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_baseentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseentry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
