# Generated by Django 4.0.5 on 2022-07-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_caseentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseentry',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to=models.CharField(blank=True, default=None, max_length=30, null=True)),
        ),
        migrations.AddField(
            model_name='caseentry',
            name='filefolder',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
