# Generated by Django 4.0.5 on 2022-08-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entrycategory_added_by_entrycategory_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseentry',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='entrycategory',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
