# Generated by Django 4.0.5 on 2022-07-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_caseentry_modified_and_more'),
    ]

    operations = [

    ]
