# Generated by Django 4.0.5 on 2022-07-11 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_baseentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEntry',
            fields=[
                ('baseentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry')),
            ],
            options={
                'verbose_name_plural': 'call entries',
            },
            bases=('entries.baseentry',),
        ),
        migrations.CreateModel(
            name='DocEntry',
            fields=[
                ('baseentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry')),
            ],
            options={
                'verbose_name_plural': 'doc entries',
            },
            bases=('entries.baseentry',),
        ),
        migrations.CreateModel(
            name='NoteEntry',
            fields=[
                ('baseentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry')),
            ],
            options={
                'verbose_name_plural': 'note entries',
            },
            bases=('entries.baseentry',),
        ),
        migrations.CreateModel(
            name='SmsEntry',
            fields=[
                ('baseentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry')),
            ],
            options={
                'verbose_name_plural': 'sms entries',
            },
            bases=('entries.baseentry',),
        ),
    ]
