# Generated by Django 4.0.5 on 2022-07-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0002_matter'),
        ('entries', '0004_entrycategory_matter'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseentry',
            name='matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matters', to='matters.matter'),
        ),
    ]
