# Generated by Django 4.0.5 on 2022-07-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_alter_baseentry_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictationEntry',
            fields=[
                ('baseentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry')),
                ('audio', models.BinaryField(null=True)),
            ],
            options={
                'verbose_name_plural': 'dictations',
            },
            bases=('entries.baseentry',),
        ),
        migrations.CreateModel(
            name='VoicemailEntry',
            fields=[
                ('baseentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry')),
                ('audio', models.BinaryField(null=True)),
            ],
            options={
                'verbose_name_plural': 'voicemails',
            },
            bases=('entries.baseentry',),
        ),
        migrations.AlterField(
            model_name='entrycategory',
            name='type',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Note'), (3, 'Phone call'), (4, 'Email'), (5, 'SMS'), (6, 'Document'), (7, 'Other'), (8, 'Voicemail'), (9, 'Dictation')], default=1),
        ),
    ]
