# Generated by Django 4.0.5 on 2022-07-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_dictationentry_voicemailentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictationentry',
            name='audiofile',
            field=models.FileField(null=True, upload_to='??'),
        ),
        migrations.AddField(
            model_name='voicemailentry',
            name='audiofile',
            field=models.FileField(null=True, upload_to='??'),
        ),
    ]
