# Generated by Django 4.0.5 on 2022-07-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='matter',
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='type',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Call'), (3, 'Wait'), (4, 'Email'), (5, 'Draft'), (6, 'Review'), (7, 'Send'), (8, 'Other'), (9, 'Pay Bill'), (10, 'Prepare Bill'), (11, 'Research'), (12, 'Fix')], default=1),
        ),
    ]
