# Generated by Django 4.0.5 on 2022-07-25 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0002_matter'),
        ('tasks', '0002_remove_task_matter_alter_taskcategory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matter_tasks', to='matters.matter'),
        ),
    ]
