# Generated by Django 4.0.5 on 2022-07-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matter',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='matter',
            name='files_foldername',
            field=models.CharField(default=models.CharField(max_length=150, unique=True), max_length=80),
        ),
    ]
