# Generated by Django 4.0.5 on 2022-07-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0002_alter_matter_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='mattertype',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
