# Generated by Django 4.0.5 on 2022-07-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0002_matter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='mattertype',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='matter',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mattertype',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
